services:
  resumeparser:
    build:
      context: .
      dockerfile: Dockerfile
    image: resumeparser:latest
    ports:
      - "8501:8501"
    env_file:
      - .env
    # Uncomment the following lines for live code updates during development
    volumes:
      - ./data:/data
